name:                trello-reminders-server
version:             0.1.0.0
github:              "omefire/trello-reminders-server"
license:             BSD3
author:              "Omar Mefire"
maintainer:          "omefire@gmail.com"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/omefire/trello-reminders-server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- opaleye
- product-profunctors
- postgresql-simple
- datetime
- email-validate
- servant-server
- warp
- regex-pcre
- transformers
- mtl
- servant
- chronos
- time
- opaleye-trans
- interpolate
- safe-exceptions
- warp-tls
- wai-cors

library:
  source-dirs: src

executables:
  trello-reminders-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trello-reminders-server
    - servant
    - wai
    - aeson
    - text

tests:
  trello-reminders-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trello-reminders-server
